In [15]:
import pandas as pd

In [16]:
df = pd.read_csv('data/song_lyrics_en.csv')
df.head()

Unnamed: 0              title  tag     artist  year   views  \
0           0          Killa Cam  rap    Cam'ron  2004  173166   
1           1         Can I Live  rap      JAY-Z  1996  468624   
2           2  Forgive Me Father  rap   Fabolous  2003    4743   
3           3       Down and Out  rap    Cam'ron  2004  144404   
4           4             Fly In  rap  Lil Wayne  2005   78271   

                                       features  \
0                   {"Cam\\'ron","Opera Steve"}   
1                                            {}   
2                                            {}   
3  {"Cam\\'ron","Kanye West","Syleena Johnson"}   
4                                            {}   

                                              lyrics  id language_cld3  \
0  [Chorus: Opera Steve & Cam'ron]\nKilla Cam, Ki...   1            en   
1  [Produced by Irv Gotti]\n\n[Intro]\nYeah, hah,...   3            en   
2  Maybe cause I'm eatin\nAnd these bastards fien...   4            en   
3  [Produced by Kanye West and Brian Miller]\n\n[...   5            en   
4  [Intro]\nSo they ask me\n"Young boy\nWhat you ...   6            en   

  language_ft language  
0          en       en  
1          en       en  
2          en       en  
3          en       en  
4          en       en

In [11]:
df['tag'].unique().size

6

In [25]:
df['artist'].size

3374198

In [10]:
df['artist'].unique().size

429060

In [21]:
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [30]:
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder

categorical_data = df['tag']

# Step 1: Label Encoding
label_encoder = LabelEncoder()
categorical_encoded = label_encoder.fit_transform(categorical_data)

# Step 2: Embedding Layer (e.g., embedding dimension is 4)
inputs = tf.keras.Input(shape=(1,))
embedding = tf.keras.layers.Embedding(input_dim=len(label_encoder.classes_), output_dim=2)(inputs)

# 建立模型
model = tf.keras.Model(inputs=inputs, outputs=embedding)
embeddings = model.predict(categorical_encoded)

print(embeddings)


105444/105444 [==============================] - 20s 187us/step
[[[-0.01602812  0.03548786]]

 [[-0.01602812  0.03548786]]

 [[-0.01602812  0.03548786]]

 ...

 [[ 0.0498409  -0.04364833]]

 [[ 0.0498409  -0.04364833]]

 [[ 0.01137866  0.01305744]]]


In [28]:
np.save('data/tag_embeddings.npy', embeddings)

In [31]:
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder

categorical_data = df['artist']

# Step 1: Label Encoding
label_encoder = LabelEncoder()
categorical_encoded = label_encoder.fit_transform(categorical_data)

# Step 2: Embedding Layer (e.g., embedding dimension is 2)
inputs = tf.keras.Input(shape=(1,))
embedding = tf.keras.layers.Embedding(input_dim=len(label_encoder.classes_), output_dim=600)(inputs)

# 建立模型
model = tf.keras.Model(inputs=inputs, outputs=embedding)
embeddings = model.predict(categorical_encoded)

print(embeddings)


105444/105444 [==============================] - 23s 218us/step
[[[-0.03651663 -0.04300829 -0.00096111 ...  0.04577483  0.03669837
   -0.01590056]]

 [[ 0.00797558  0.01449763  0.02677281 ...  0.01654521  0.02038094
    0.02224332]]

 [[ 0.02283705  0.04656899 -0.03825787 ...  0.01336754 -0.03642181
   -0.01813016]]

 ...

 [[ 0.03346798  0.04224289 -0.01522952 ...  0.0296445   0.01737833
    0.02957953]]

 [[ 0.01954523 -0.03824783 -0.03105472 ... -0.00585253 -0.03867667
    0.04979784]]

 [[ 0.01157088  0.03679362 -0.04599215 ...  0.04691451 -0.02084425
   -0.04081484]]]


In [32]:
np.save('data/artist_embeddings.npy', embeddings)