In [27]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/song_lyrics_en.csv')

df.head()

Unnamed: 0.2  Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1              title  \
0             0           0             0               0          Killa Cam   
1             1           1             1               1         Can I Live   
2             2           2             2               2  Forgive Me Father   
3             3           3             3               3       Down and Out   
4             4           4             4               4             Fly In   

   tag     artist  year   views                             features  \
0  rap    Cam'ron  2004  173166                 Cam\\ron Opera Steve   
1  rap      JAY-Z  1996  468624                                  NaN   
2  rap   Fabolous  2003    4743                                  NaN   
3  rap    Cam'ron  2004  144404  Cam\\ron Kanye West Syleena Johnson   
4  rap  Lil Wayne  2005   78271                                  NaN   

                                              lyrics  id language_cld3  \
0  Killa Cam, Killa Cam, Cam\nKilla Cam, Killa Ca...   1            en   
1  Yeah, hah, yeah, Roc-A-Fella\nWe invite you to...   3            en   
2  Maybe cause I'm eatin\nAnd these bastards fien...   4            en   
3  Ugh, Killa!\nBaby!\nKanye, this that 1970s Her...   5            en   
4  So they ask me\n"Young boy\nWhat you gon' do t...   6            en   

  language_ft language popularity_bin  \
0          en       en         Medium   
1          en       en         Medium   
2          en       en       Very Low   
3          en       en         Medium   
4          en       en            Low   

                                      lyrics_cleaned  \
0  Killa Cam, Killa Cam, Cam\nKilla Cam, Killa Ca...   
1  Yeah, hah, yeah, Roc-A-Fella\nWe invite you to...   
2  Maybe cause I'm eatin\nAnd these bastards fien...   
3  Ugh, Killa!\nBaby!\nKanye, this that 1970s Her...   
4  So they ask me\n"Young boy\nWhat you gon' do t...   

                       feature_cleaned  \
0                 Cam\\ron Opera Steve   
1                                  NaN   
2                                  NaN   
3  Cam\\ron Kanye West Syleena Johnson   
4                                  NaN   

                                       song_document  
0  Killa Cam Killa Cam, Killa Cam, Cam\nKilla Cam...  
1  Can I Live Yeah, hah, yeah, Roc-A-Fella\nWe in...  
2  Forgive Me Father Maybe cause I'm eatin\nAnd t...  
3  Down and Out Ugh, Killa!\nBaby!\nKanye, this t...  
4  Fly In So they ask me\n"Young boy\nWhat you go...

In [25]:
df = df[['tag', 'artist', 'views', 'popularity_bin', 'song_document']]

In [26]:
df.to_csv('/content/drive/MyDrive/Colab Notebooks/song_lyrics_en.csv')

In [28]:
slice_num = 10000
df = df[:slice_num]

In [29]:
! python -m spacy download en_core_web_md


Exception ignored in: <function _get_module_lock.<locals>.cb at 0x7d4a533e9fc0>
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 198, in cb
KeyboardInterrupt: 
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.10/dist-packages/spacy/__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "/usr/local/lib/python3.10/dist-packages/spacy/errors.py", line 3, in <module>
    from .compat import Literal
  File "/usr/local/lib/python3.10/dist-packages/spacy/compat.py", line 4, in <module>
    from thinc.util import copy_array
  File "/usr/local/lib/python3.10/

In [30]:
import spacy
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tqdm import tqdm, tqdm_pandas

tqdm_pandas(tqdm())

nlp = spacy.load('en_core_web_md')
tag_embeddings = np.load('/content/drive/MyDrive/Colab Notebooks/tag_embeddings.npy')
artist_embeddings = np.load('/content/drive/MyDrive/Colab Notebooks/artist_embeddings.npy')

tag_embeddings

0it [00:00, ?it/s]
0it [37:12, ?it/s]
/usr/local/lib/python3.10/dist-packages/spacy/util.py:1740: UserWarning: [W111] Jupyter notebook detected: if using `prefer_gpu()` or `require_gpu()`, include it in the same cell right before `spacy.load()` to ensure that the model is loaded on the correct device. More information: http://spacy.io/usage/v3#jupyter-notebook-gpu
  warnings.warn(Warnings.W111)


array([[[-0.04503907,  0.0417758 ,  0.01997494]],

       [[-0.04503907,  0.0417758 ,  0.01997494]],

       [[-0.04503907,  0.0417758 ,  0.01997494]],

       ...,

       [[-0.03446241,  0.01993293,  0.01982058]],

       [[-0.03446241,  0.01993293,  0.01982058]],

       [[ 0.00429112,  0.00109095,  0.01435422]]], dtype=float32)

In [31]:
tag_embeddings = tag_embeddings[:, 0, :]
tag_embeddings = tag_embeddings[:slice_num]
tag_embeddings

array([[-0.04503907,  0.0417758 ,  0.01997494],
       [-0.04503907,  0.0417758 ,  0.01997494],
       [-0.04503907,  0.0417758 ,  0.01997494],
       ...,
       [-0.04503907,  0.0417758 ,  0.01997494],
       [-0.04503907,  0.0417758 ,  0.01997494],
       [-0.04503907,  0.0417758 ,  0.01997494]], dtype=float32)

In [32]:
artist_embeddings = artist_embeddings[:, 0, :]
artist_embeddings = artist_embeddings[:slice_num]
artist_embeddings

array([[-0.03651663, -0.04300829, -0.00096111, ...,  0.04577483,
         0.03669837, -0.01590056],
       [ 0.00797558,  0.01449763,  0.02677281, ...,  0.01654521,
         0.02038094,  0.02224332],
       [ 0.02283705,  0.04656899, -0.03825787, ...,  0.01336754,
        -0.03642181, -0.01813016],
       ...,
       [ 0.00858756, -0.04817573,  0.0425526 , ..., -0.02735157,
         0.03027593,  0.00185962],
       [ 0.00858756, -0.04817573,  0.0425526 , ..., -0.02735157,
         0.03027593,  0.00185962],
       [ 0.00858756, -0.04817573,  0.0425526 , ..., -0.02735157,
         0.03027593,  0.00185962]], dtype=float32)

In [ ]:
# ! pip install transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 21.2 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 20.6 MB/s eta 0:00:00


In [33]:
from transformers import BertTokenizer, TFBertModel
import tensorflow as tf

# 檢查是否有可用的 GPU
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

# 加載預訓練的 BERT 模型和 tokenizer
bert_model = TFBertModel.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# 示例文本數據 (實際上是你的文本數據集)
texts = df['song_document'].tolist()

import numpy as np

batch_size = 32  # 調整這個數字來適應可用的 GPU 記憶體
num_batches = int(np.ceil(len(texts) / batch_size))

all_cls_embeddings = []

for i in range(num_batches):
    batch_texts = texts[i * batch_size:(i + 1) * batch_size]
    encoded_inputs = tokenizer(batch_texts, return_tensors='tf', padding=True, truncation=True, max_length=128)

    # 將數據移動到 GPU 上，並處理該批次
    with tf.device('/GPU:0'):
        bert_outputs = bert_model(encoded_inputs)

    # 提取 [CLS] token 的嵌入
    cls_embeddings = bert_outputs.last_hidden_state[:, 0, :]
    all_cls_embeddings.append(cls_embeddings)

# 將所有批次的結果合併
all_cls_embeddings = tf.concat(all_cls_embeddings, axis=0)

Num GPUs Available:  1


Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [34]:
import numpy as np


# Convert the other features to TensorFlow tensors
artist_embeddings_tf = tf.convert_to_tensor(artist_embeddings, dtype=tf.float32)
tag_embeddings_tf = tf.convert_to_tensor(tag_embeddings, dtype=tf.float32)

# Concatenate the BERT embeddings with the other feature embeddings
combined_embeddings = tf.concat([all_cls_embeddings, tag_embeddings_tf, artist_embeddings_tf], axis=1)

# Combined shape: (batch_size, hidden_size + other_feature_size)
print(combined_embeddings.shape)


(10000, 1371)


In [35]:
def transform_y(label):
    if label == 'Very Low':
        return 0
    if label == 'Low':
        return 1
    if label == 'Medium':
        return 2
    if label == 'High':
        return 3
    if label == 'Very High':
        return 4

y = df['popularity_bin'].apply(transform_y).values

In [15]:
y.shape

(10000,)

In [36]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

# Assuming X and y are your input and output arrays
# X.shape = (10000, 903), y.shape = (10000,)

# Convert y to one-hot encoded format for multi-class classification
y_one_hot = to_categorical(y, num_classes=5)
y_one_hot

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [37]:
X_train, X_test, y_train, y_test = train_test_split(combined_embeddings.numpy(), y_one_hot, test_size=0.1, random_state=42)


In [20]:
y_train.shape

(8000, 5)

In [38]:
from tensorflow.keras import backend as K

def f1_score(y_true, y_pred):
    y_pred_classes = K.argmax(y_pred, axis=-1)
    y_true_classes = K.argmax(y_true, axis=-1)

    precision = tf.metrics.Precision()(y_true_classes, y_pred_classes)
    recall = tf.metrics.Recall()(y_true_classes, y_pred_classes)

    f1 = 2 * ((precision * recall) / (precision + recall + K.epsilon()))
    return f1

In [39]:
model1 = Sequential()

# Input layer and first hidden layer (Dense)
model1.add(Dense(128, input_dim=1371, activation='relu'))  # Input dim matches the number of features in X

# Add additional hidden layers as needed
model1.add(Dense(64, activation='relu'))

# Output layer (for 5 classes)
model1.add(Dense(5, activation='softmax'))  # Softmax for multi-class classification


model1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model1.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.2)

loss, accuracy = model1.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.2f}")


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.5445 - loss: 1.0764 - val_accuracy: 0.6117 - val_loss: 0.9576
Epoch 2/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6304 - loss: 0.9049 - val_accuracy: 0.6417 - val_loss: 0.8700
Epoch 3/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6384 - loss: 0.8564 - val_accuracy: 0.6494 - val_loss: 0.8460
Epoch 4/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6776 - loss: 0.7769 - val_accuracy: 0.6328 - val_loss: 0.8703
Epoch 5/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6793 - loss: 0.7670 - val_accuracy: 0.6172 - val_loss: 0.8834
Epoch 6/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6941 - loss: 0.7397 - val_accuracy: 0.6528 - val_loss: 0.8541
Epoch 7/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.6911 - val_accuracy: 0.6428 - val_loss: 0.8463
Epoch 8/20
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7137 - loss: 0.6772 - val_accuracy: 0.

In [40]:
from sklearn.metrics import f1_score
import numpy as np

# Get predictions from the model (these will be probabilities)
y_pred_prob = model1.predict(X_test)

# Convert probabilities to class predictions (e.g., the index of the max value)
y_pred = np.argmax(y_pred_prob, axis=1)

# If y_test is one-hot encoded, convert it back to class labels
y_test_class = np.argmax(y_test, axis=1)

# Calculate the F1 score using sklearn
f1 = f1_score(y_test_class, y_pred, average='weighted')

# Print the F1 score
print(f"Test F1 Score: {f1:.2f}")


32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
Test F1 Score: 0.60
